Remove ribbon when technology list is empty, or matches root path
hqhhuang/swift-docc-render pull request #4
Opened 2022-03-04 06:27 UTC by hqhhuang

Bug/issue #, if applicable: 88214559, 89672818

## Summary
1. The grey ribbon shouldn't be present if the technology list is empty
2. We should hide "framework" metadata on pages where that info matches the root framework in the breadcrumb.

## Testing
Steps:
To test #1, go to a `SlothCreator` page.

To test #2, if you have access to a documentation archive that includes a page where the “framework” metadata does not match the root framework in the breadcrumb, navigate to the page and verify that the ribbon is not rendered.

## Checklist
- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary - NA

2022-03-04 07:19 UTC, dobromir-hristov requested changes

2022-03-04 07:19 UTC, dobromir-hristov commented on src/components/DocumentationTopic.vue
> +      // const root = this.identifier.split('/documentation/')[-1].split('/')[0];
```suggestion
```

2022-03-04 07:19 UTC, dobromir-hristov commented on src/components/DocumentationTopic.vue
> +      return !hideSummary && (shouldShowLanguageSwitcher || showmodules);
Should we add `extendsTechnology` too?

2022-03-04 07:19 UTC, dobromir-hristov commented on src/views/DocumentationTopic.vue
> +          :rootPath="technology.title"
Probably rootTitle is a better name, since we dont pass a path?

2022-03-04 07:19 UTC, dobromir-hristov commented on tests/unit/components/DocumentationTopic.spec.js
> +    it('renders the Summary, if more than 1 module', () => {
I dont see a test to hide the summary.

2022-03-04 18:48 UTC, marinaaisa requested changes
I added some refactor suggestions :)

2022-03-04 18:48 UTC, marinaaisa commented on src/components/DocumentationTopic.vue
> +    showModules() {
I suggest simplifying this computed property as:

```js
showModules({ modules, rootPath }) {
  // show modules if page belongs to multiple technologies or if name doesn't match root of page
  if (!modules) return false;
  return rootPath !== modules[0].name || modules.length > 1;
},
```

2022-03-04 18:48 UTC, marinaaisa commented on src/components/DocumentationTopic.vue
> +    showSummary({ shouldShowLanguageSwitcher, showmodules }) {
```suggestion
    showSummary({ shouldShowLanguageSwitcher, showModules }) {
```

2022-03-04 18:48 UTC, marinaaisa commented on src/components/DocumentationTopic.vue
> +      return !hideSummary && (shouldShowLanguageSwitcher || showmodules);
```suggestion
      return !hideSummary && (shouldShowLanguageSwitcher || showModules);
```

2022-03-04 18:48 UTC, marinaaisa commented on tests/unit/components/DocumentationTopic.spec.js
> +      // wrapper = shallowMount(DocumentationTopic, { propsData });
```suggestion
```

2022-03-04 19:00 UTC, dobromir-hristov commented on src/components/DocumentationTopic.vue
> +    showModules() {
Need to make sure modules is not an empty array

2022-03-15 15:44 UTC, hqhhuang commented
Issue was fixed with: https://github.com/hqhhuang/swift-docc-render/pull/8
Closing this PR

2022-03-15 15:44 UTC, closed without merging